services:
  api:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - postgres
    env_file:
      - ./.env
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=kareem.master
      - DB_HOSTNAME=postgres
      - DB_NAME=production
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=kareem.master
      - POSTGRES_DB=production
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:


